# name: Build and Push Docker image

# on:
#   push:
#     branches:
#       - main
#       - enhancement/**  # optional: builds on enhancement branches too
#   pull_request:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout source code
#         uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           push: true
#           tags: nikhil635/graphgen-ai:latest

name: Build and Push Docker image

on:
  push:
    branches:
      - main
      - enhancement/**  # optional: builds on enhancement branches too
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag
        id: set_tag
        run: echo "::set-output name=image_tag::nikhil635/graphgen-ai:latest"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: nikhil635/graphgen-ai:latest

  scan:
    name: Scan Docker Image with Trivy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.build.outputs.image_tag }}
          format: 'table'
          exit-code: 0  # Set to '1' if you want to fail on vulnerabilities
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'


